### ISSUE TITLE
RiTa.trimPunctuation strip only one character?

### ISSUE THREAD

**Issue by dhowe** [dhowe/RiTa#465] opened 2017-06-11 03:54 UTC
from @shadoof:

> Question: does RiTa.trimPunctuation only strip off one character layer? i.e.
> 
> "here?'" --> "here?" rather than --> "here"
> 
> If not, then RiTa.trimPunctuation (and stripPunctuation?) may not be handling "?" correctly.

**Comment by cqx931** [comment] 2017-06-14 03:04
When I test `RiTa.trimPunctuation("here?'")` in rita v1.2.12, I do get "here", rather than "here?".
Same result for stripPunctuation.

**Comment by dhowe** [comment] 2017-06-19 04:39
@shadoof ?

**Comment by shadoof** [comment] 2017-06-20 14:55
Punctuation is tricky. I noticed this when hoping to trim `here?’` which has a final *curly* quote. If curly or smart quotes are not counted as punctuation, then the curly quote is not trimmed and the `?` (question mark) is protected. The protection is *good* to have, esp. for forms such as "don't" and "don’t" but to ensure the behavior I wanted I had to add the line 1178
```
key = key.replace(/’|‘|\?/g, '');
```
to a makeKey() function in readers-app.js.

You might want to implement a flag or parameter for:
* treat-single-curly-quotes-as-punctuation (treat double curly quotes as punctuation is probably not needed since they are always punctuation, in Global English anyway. The problem is that right-curly-quote, or `'` for that matter is like a 'proper' letter standing for an ellipsis in word-sized tokens)

Then you'd also need code for this pseudo code:
```
if (treat-single-curly-quotes-as-punctuation && (other non-white-space-punctuation marks
*precede* the curly quote))
    trim them all
```
... because you would not want to trim forms like `’69` or `’nuff said`.

**Comment by shadoof** [comment] 2017-06-20 15:00
Note: trimPunctuation is great to have (I should add) and I think that best practices in handling punctuation would most often indicate doing this at the token level rather than the line or sentence (unless there are good reasons to do otherwise).

Thus, it might be good to have the stripPunctuation(x) function work like this:
```
stripPunctuation(s)
    for (tokens in s)
        trimPunctuation(s[i])
```

**Comment by dhowe** [comment] 2017-07-08 05:11
@shadoof  we've added curly quotes to both stripPunctuation and trimPunctuation -- are there any other specific cases where those functions are not doing what they should (or what you expect) ? if so, please list below...

**Comment by shadoof** [comment] 2018-07-12 16:33
@dhowe verified that this is working as it should in 1.3.11 (is this the latest public version?) and closing

**Closed by shadoof** 2018-07-12 16:33 UTC
Labels: PRIORITY: Low, needs-verification

**Comment by dhowe** [comment] 2018-07-12 16:37
we're at 1.3.82 now

**Comment by shadoof** [comment] 2018-07-12 16:52
@dhowe I saw that but tried to update using npm and am now unclear about best way to do this (from what directory do I issue what command? - i have tried to rtfm btw ;)

**Comment by dhowe** [comment] 2018-07-12 17:04
https://docs.npmjs.com/getting-started/updating-local-packages
https://docs.npmjs.com/getting-started/updating-global-packages
